const leads = [
  {
    id: 1,
    name: "John Dente",
    contact: "john.dente@example.com",
    source: "Linkedin",
    interest_level: "high",
    status: "new",
    assigned_to: "John Doe",
  },
  {
    id: 2,
    name: "Zed Doe",
    contact: "jane.doe@example.com",
    source: "Google",
    interest_level: "medium",
    status: "new",
    assigned_to: "Jeff Bezos",
  },
  {
    id: 3,
    name: "Tim Smith",
    contact: "john.smith@example.com",
    source: "Google",
    interest_level: "low",
    status: "old",
    assigned_to: "John Doe",
  },
  {
    id: 4,
    name: "Jane Smith",
    contact: "jane.smith@example.com",
    source: "Google",
    interest_level: "high",
    status: "old",
    assigned_to: "John Doe",
  },
  {
    id: 5,
    name: "John Doe",
    contact: "john.doe@example.com",
    source: "Google",
    interest_level: "high",
    status: "new",
    assigned_to: "John Doe",
  },
  {
    id: 6,
    name: "George Allen",
    contact: "george.allen@example.com",
    source: "Google",
    interest_level: "high",
    status: "new",
    assigned_to: "John Doe",
  },
  {
    id: 7,
    name: "Carry Underwood",
    contact: "carry.underwood@example.com",
    source: "Linkedin",
    interest_level: "low",
    status: "new",
    assigned_to: "John Doe",
  },
  {
    id: 8,
    name: "Jerry Seinfeld",
    contact: "jerry.seinfeld@example.com",
    source: "Google",
    interest_level: "high",
    status: "old",
    assigned_to: "Jeff Bezos",
  },
];

export default leads;